[book]
title = "Data Analysis in Rust"
authors = ["Eric Fecteau"]
language = "en"
src = "src_processed"

[output.html]
git-repository-url = "https://github.com/EricFecteau/rust-data-analysis"

[output.html.playground]
runnable = false